---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-node1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      kubernetes.io/hostname: worker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-node2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      kubernetes.io/hostname: worker1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-node3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      kubernetes.io/hostname: worker2

